const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 10.99,
    image: "../public/book1.jpg",
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 8.99,
    image: "../public/book2.jpg",
  },
  {
    id: 3,
    title: "1984",
    author: "George Orwell",
    price: 9.99,
    image: "../public/book3.jpg",
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 7.99,
    image: "../public/book4.jpg",
  },
  {
    id: 5,
    title: "Moby Dick",
    author: "Herman Melville",
    price: 11.99,
    image: "../public/book5.jpg",
  },
  {
    id: 6,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 10.49,
    image: "../public/book6.jpg",
  },
  {
    id: 7,
    title: "War and Peace",
    author: "Leo Tolstoy",
    price: 14.99,
    image: "../public/book7.jpg",
  },
  {
    id: 8,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    price: 9.49,
    image: "../public/book8.jpg",
  },
  {
    id: 9,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 12.99,
    image: "../public/book9.jpg",
  },
  {
    id: 10,
    title: "Brave New World",
    author: "Aldous Huxley",
    price: 10.29,
    image: "../public/book10.jpg",
  },
  {
    id: 11,
    title: "Ulysses",
    author: "James Joyce",
    price: 13.99,
    image: "../public/book11.jpg",
  },
  {
    id: 12,
    title: "The Odyssey",
    author: "Homer",
    price: 8.49,
    image: "../public/book12.jpg",
  },
  {
    id: 13,
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    price: 15.99,
    image: "../public/book13.jpg",
  },
  {
    id: 14,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    price: 11.29,
    image: "../public/book14.jpg",
  },
  {
    id: 15,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    price: 9.79,
    image: "../public/book15.jpg",
  },
  {
    id: 16,
    title: "The Iliad",
    author: "Homer",
    price: 7.99,
    image: "../public/book16.jpg",
  },
  {
    id: 17,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    price: 12.49,
    image: "../public/book17.jpg",
  },
  {
    id: 18,
    title: "Frankenstein",
    author: "Mary Shelley",
    price: 6.99,
    image: "../public/book18.jpg",
  },
  {
    id: 19,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    price: 9.49,
    image: "../public/book19.jpg",
  },
  {
    id: 20,
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    price: 13.49,
    image: "../public/book20.jpg",
  },
  {
    id: 21,
    title: "Les Misérables",
    author: "Victor Hugo",
    price: 14.99,
    image: "../public/book21.jpg",
  },
  {
    id: 22,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    price: 8.29,
    image: "../public/book22.jpg",
  },
  {
    id: 23,
    title: "Dracula",
    author: "Bram Stoker",
    price: 7.49,
    image: "../public/book23.jpg",
  },
];
